spring.application.name=CricTribe
spring.datasource.url=jdbc:postgresql://localhost:5432/crictribe_db?currentSchema=public
spring.datasource.username=crictribe_admin
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=public
jwt.secret=your_super_secret_key_123456
server.port=8080